<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="NAVMCTMTTL108" name="com.colt.qa.apttestscripts.APT_MCS_CreateAccessCoreDevice_Prizmnet" tests="1" failures="0" timestamp="22 Aug 2020 23:02:57 GMT" time="933.645" errors="1">
  <testcase name="createAccessCoreDevice" time="933.645" classname="com.colt.qa.apttestscripts.APT_MCS_CreateAccessCoreDevice_Prizmnet">
    <error type="java.lang.AssertionError" message="expected [GMT] but found [ize]">
      <![CDATA[java.lang.AssertionError: expected [GMT] but found [ize]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.colt.qa.scripthelpers.APT_CreateAccessCoreDevice_ManageNetworkHelper.verifyFetchInterface(APT_CreateAccessCoreDevice_ManageNetworkHelper.java:595)
	at com.colt.qa.apttestscripts.APT_MCS_CreateAccessCoreDevice_Prizmnet.createAccessCoreDevice(APT_MCS_CreateAccessCoreDevice_Prizmnet.java:172)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- createAccessCoreDevice -->
</testsuite> <!-- com.colt.qa.apttestscripts.APT_MCS_CreateAccessCoreDevice_Prizmnet -->
