<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ULVMCTMTTL104" name="com.saksoft.qa.apttestscripts.Hss" tests="9" failures="9" timestamp="17 Jun 2020 06:10:10 GMT" time="0.000" errors="0">
  <testcase name="VerifyManagementPanel" time="0.000" classname="com.saksoft.qa.apttestscripts.Hss">
    <failure type="org.testng.TestNGException" message="
Method public void com.saksoft.qa.apttestscripts.Hss.VerifyManagementPanel(java.util.Map) throws java.lang.Exception requires a @DataProvider named : DataReader_createService_Hss in class com.saksoft.qa.excellibrary.APT_DataReader_SS">
      <![CDATA[org.testng.TestNGException: 
Method public void com.saksoft.qa.apttestscripts.Hss.VerifyManagementPanel(java.util.Map) throws java.lang.Exception requires a @DataProvider named : DataReader_createService_Hss in class com.saksoft.qa.excellibrary.APT_DataReader_SS
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:268)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:417)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- VerifyManagementPanel -->
  <testcase name="VerifyOrderPanel" time="0.000" classname="com.saksoft.qa.apttestscripts.Hss">
    <failure type="org.testng.TestNGException" message="
Method public void com.saksoft.qa.apttestscripts.Hss.VerifyOrderPanel(java.util.Map) throws java.lang.Exception requires a @DataProvider named : DataReader_createService_Hss in class com.saksoft.qa.excellibrary.APT_DataReader_SS">
      <![CDATA[org.testng.TestNGException: 
Method public void com.saksoft.qa.apttestscripts.Hss.VerifyOrderPanel(java.util.Map) throws java.lang.Exception requires a @DataProvider named : DataReader_createService_Hss in class com.saksoft.qa.excellibrary.APT_DataReader_SS
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:268)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:417)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- VerifyOrderPanel -->
  <testcase name="fillvaluesServiceOrder" time="0.000" classname="com.saksoft.qa.apttestscripts.Hss">
    <failure type="org.testng.TestNGException" message="
Method public void com.saksoft.qa.apttestscripts.Hss.fillvaluesServiceOrder(java.util.Map) throws java.lang.Exception requires a @DataProvider named : DataReader_createService_Hss in class com.saksoft.qa.excellibrary.APT_DataReader_SS">
      <![CDATA[org.testng.TestNGException: 
Method public void com.saksoft.qa.apttestscripts.Hss.fillvaluesServiceOrder(java.util.Map) throws java.lang.Exception requires a @DataProvider named : DataReader_createService_Hss in class com.saksoft.qa.excellibrary.APT_DataReader_SS
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:268)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:417)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- fillvaluesServiceOrder -->
  <testcase name="VerifyServicecreatedPanel" time="0.000" classname="com.saksoft.qa.apttestscripts.Hss">
    <failure type="org.testng.TestNGException" message="
Method public void com.saksoft.qa.apttestscripts.Hss.VerifyServicecreatedPanel(java.util.Map) throws java.lang.Exception requires a @DataProvider named : DataReader_createService_Hss in class com.saksoft.qa.excellibrary.APT_DataReader_SS">
      <![CDATA[org.testng.TestNGException: 
Method public void com.saksoft.qa.apttestscripts.Hss.VerifyServicecreatedPanel(java.util.Map) throws java.lang.Exception requires a @DataProvider named : DataReader_createService_Hss in class com.saksoft.qa.excellibrary.APT_DataReader_SS
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:268)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:417)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- VerifyServicecreatedPanel -->
  <testcase name="chooseCustomer" time="0.000" classname="com.saksoft.qa.apttestscripts.Hss">
    <failure type="org.testng.TestNGException" message="
Method public void com.saksoft.qa.apttestscripts.Hss.chooseCustomer(java.util.Map) throws java.lang.Exception requires a @DataProvider named : DataReader_createService_Hss in class com.saksoft.qa.excellibrary.APT_DataReader_SS">
      <![CDATA[org.testng.TestNGException: 
Method public void com.saksoft.qa.apttestscripts.Hss.chooseCustomer(java.util.Map) throws java.lang.Exception requires a @DataProvider named : DataReader_createService_Hss in class com.saksoft.qa.excellibrary.APT_DataReader_SS
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:268)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:417)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- chooseCustomer -->
  <testcase name="verifySelectServicetype" time="0.000" classname="com.saksoft.qa.apttestscripts.Hss">
    <failure type="org.testng.TestNGException" message="
Method public void com.saksoft.qa.apttestscripts.Hss.verifySelectServicetype(java.util.Map) throws java.lang.Exception requires a @DataProvider named : DataReader_createService_Hss in class com.saksoft.qa.excellibrary.APT_DataReader_SS">
      <![CDATA[org.testng.TestNGException: 
Method public void com.saksoft.qa.apttestscripts.Hss.verifySelectServicetype(java.util.Map) throws java.lang.Exception requires a @DataProvider named : DataReader_createService_Hss in class com.saksoft.qa.excellibrary.APT_DataReader_SS
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:268)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:417)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- verifySelectServicetype -->
  <testcase name="VerifyAddDevice" time="0.000" classname="com.saksoft.qa.apttestscripts.Hss">
    <failure type="org.testng.TestNGException" message="
Method public void com.saksoft.qa.apttestscripts.Hss.VerifyAddDevice(java.util.Map) throws java.lang.Exception requires a @DataProvider named : DataReader_createService_Hss in class com.saksoft.qa.excellibrary.APT_DataReader_SS">
      <![CDATA[org.testng.TestNGException: 
Method public void com.saksoft.qa.apttestscripts.Hss.VerifyAddDevice(java.util.Map) throws java.lang.Exception requires a @DataProvider named : DataReader_createService_Hss in class com.saksoft.qa.excellibrary.APT_DataReader_SS
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:268)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:417)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- VerifyAddDevice -->
  <testcase name="verifyServicePanelAction" time="0.000" classname="com.saksoft.qa.apttestscripts.Hss">
    <failure type="org.testng.TestNGException" message="
Method public void com.saksoft.qa.apttestscripts.Hss.verifyServicePanelAction(java.util.Map) throws java.lang.Exception requires a @DataProvider named : DataReader_createService_Hss in class com.saksoft.qa.excellibrary.APT_DataReader_SS">
      <![CDATA[org.testng.TestNGException: 
Method public void com.saksoft.qa.apttestscripts.Hss.verifyServicePanelAction(java.util.Map) throws java.lang.Exception requires a @DataProvider named : DataReader_createService_Hss in class com.saksoft.qa.excellibrary.APT_DataReader_SS
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:268)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:417)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- verifyServicePanelAction -->
  <testcase name="verifyListofFieldsForOrderandServicetype" time="0.000" classname="com.saksoft.qa.apttestscripts.Hss">
    <failure type="org.testng.TestNGException" message="
Method public void com.saksoft.qa.apttestscripts.Hss.verifyListofFieldsForOrderandServicetype(java.util.Map) throws java.lang.Exception requires a @DataProvider named : DataReader_createService_Hss in class com.saksoft.qa.excellibrary.APT_DataReader_SS">
      <![CDATA[org.testng.TestNGException: 
Method public void com.saksoft.qa.apttestscripts.Hss.verifyListofFieldsForOrderandServicetype(java.util.Map) throws java.lang.Exception requires a @DataProvider named : DataReader_createService_Hss in class com.saksoft.qa.excellibrary.APT_DataReader_SS
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:268)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:417)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- verifyListofFieldsForOrderandServicetype -->
</testsuite> <!-- com.saksoft.qa.apttestscripts.Hss -->
